// <auto-generated />
namespace Roasts_and_Rants.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201801141914407_DropAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
